# Homebrew formula for kosa8.
#
# Regenerated by CI on every release (see the kosa8-releases workflow), so
# `brew upgrade kosa8` tracks new versions without a manual edit.
class Kosa8 < Formula
  desc "Run AI coding assistants in sealed machines you can save and copy"
  homepage "https://kosa8.com"
  license "Apache-2.0"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/AzmxAI/kosa8-releases/releases/download/v#{version}/kosa8_#{version}_darwin_arm64.zip"
      sha256 "4ba5f57eae7f810310e8dfef55a7b81f39268284ec33e22ccee1852137a86ac3"
    else
      url "https://github.com/AzmxAI/kosa8-releases/releases/download/v#{version}/kosa8_#{version}_darwin_amd64.zip"
      sha256 "9338e901d519d0c0db3e707318728d71f068f9384a7c5c2b404f931850c15590"
    end
  end

  def install
    bin.install "kosa8"
    # kosa8d only ships for Apple Silicon: it drives Virtualization.framework,
    # which needs an arm64 Mac. Intel Macs get the CLI as a remote client.
    bin.install "kosa8d" if Hardware::CPU.arm? && File.exist?("kosa8d")
  end

  def caveats
    return unless Hardware::CPU.intel?
    <<~EOS
      This Mac has an Intel processor, so it cannot run containers itself.
      kosa8 is installed as a client — point it at an Apple Silicon Mac:

        export KOSA8_HOST=https://your-mac.example.com
        export KOSA8_TOKEN=…
    EOS
  end

  test do
    assert_match "kosa8 client", shell_output("#{bin}/kosa8 version")
  end
end
