# Homebrew formula for kosa8.
#
# Regenerated by CI on every release (see the kosa8-releases workflow), so
# `brew upgrade kosa8` tracks new versions without a manual edit.
class Kosa8 < Formula
  desc "Run AI coding assistants in sealed machines you can save and copy"
  homepage "https://kosa8.com"
  license "Apache-2.0"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/AzmxAI/kosa8-releases/releases/download/v#{version}/kosa8_#{version}_darwin_arm64.zip"
      sha256 "f96d7f67c63fc67706ff20c672026ce498c660c9d915e54de10fc839fbb855de"
    else
      url "https://github.com/AzmxAI/kosa8-releases/releases/download/v#{version}/kosa8_#{version}_darwin_amd64.zip"
      sha256 "b255f3877382e2f0a087f8f6cd4312a719d0210ee835b1db562ef8474d55e5b0"
    end
  end

  def install
    bin.install "kosa8"
    # kosa8d only ships for Apple Silicon: it drives Virtualization.framework,
    # which needs an arm64 Mac. Intel Macs get the CLI as a remote client.
    bin.install "kosa8d" if Hardware::CPU.arm? && File.exist?("kosa8d")
  end

  def caveats
    return unless Hardware::CPU.intel?
    <<~EOS
      This Mac has an Intel processor, so it cannot run containers itself.
      kosa8 is installed as a client — point it at an Apple Silicon Mac:

        export KOSA8_HOST=https://your-mac.example.com
        export KOSA8_TOKEN=…
    EOS
  end

  test do
    assert_match "kosa8 client", shell_output("#{bin}/kosa8 version")
  end
end
